albums:
  primary: "https://open.spotify.com/album/4lJ0vy0SIlMxHYofabpjng" 
  alternates:
    - "https://open.spotify.com/album/75NdpQFqXPKVRJn8bqEADO"
    - "https://open.spotify.com/album/3JFryzZ2dByJ7Z2Ik2fVua"
    - "https://open.spotify.com/album/2yMi2lDSI8eZ3GND3TBirR"
    - "https://open.spotify.com/album/567Z7PXaLCXKcEDJXrHvk4"
    - "https://open.spotify.com/album/280qsfdC5fp2a9W00GT8iO"
    - "https://open.spotify.com/album/0DzshtAR827cBKDjpg00EW"
    - "https://open.spotify.com/album/7wO57SU1FSaI0T5D7ihWqn"
    - "https://open.spotify.com/album/7ymYtcn91u3FY8P07QKO53"
    - "https://open.spotify.com/album/0mHI2ldIP9spGGPe9Ga2Ua"
    - "https://open.spotify.com/album/3hj77nYJUvYUpGtZv8JPvB"
    - "https://open.spotify.com/album/7u66tmYVMMEgIRbSrvKNVI"
    - "https://open.spotify.com/album/2dFMdArzhieL38xrO5S5Bv"
    - "https://open.spotify.com/album/6MXM5OM3TjFsYtOQJVBxtu"
    - "https://open.spotify.com/album/2fiEH2ugttiqfcOsF3jnuR"
    - "https://open.spotify.com/album/5SK12JSVkcolbcbkvk1wIh"
    - "https://open.spotify.com/album/5UUYCSMFDpzrcgWAVcTt04"
    - "https://open.spotify.com/album/01GSxr1MJXtF60MzlcWo42"
    - "https://open.spotify.com/album/2uUW5Muj7sQi7YFsO8rmWU"
    - "https://open.spotify.com/album/2KCDPBM4TRwPqDLFgl5tVw"
    - "https://open.spotify.com/album/0YwEPMrUAAcw1AWPnfrxoV"
    - "https://open.spotify.com/album/4HRI2HpwN3L9X3cPoQlBI5"
    - "https://open.spotify.com/album/28cSU3x5oczLYrVQ5lNjmF"
    - "https://open.spotify.com/album/5yTOYdXFtLZ4aBx92xjwpm"
    - "https://open.spotify.com/album/3MNWfrmnJ0JTRAj07yKIYM"
